// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfwtdecyycnhaywriaaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmd3RkZWN5eWNuaGF5d3JpYWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjIxNjIsImV4cCI6MjA1ODczODE2Mn0.91FMmE-dF3h3kis8GYTihq5hDn7nA3sn6vvVa3Qnn4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);